### PR TITLE
Update tedivm/jshrink to upstream version 1.3.2

### PR DESCRIPTION
**Pull request by ahukkanen**
Apply all the changes in tedivm/jshrink between versions 1.1.0 and 1.3.2.

Related discussion:
https://github.com/concrete5/concrete5/issues/7907

### CODE REVIEW

**Comment by mlocati** [comment]
Did you try to apply both jshrink patches (the one currently in this repo and your one)? I think that they are conflicting...

**Comment by ahukkanen** [comment]
@mlocati Yes, I ran composer install against this patched version. Here is how the previous patch's lines look like after composer install:

c5-patch

**Comment by ahukkanen** [comment]
@mlocati Also note that your patch is applied first which is why I think it is working properly.

**Comment by mlocati** [comment]
I think that we may discard the patch currently present in this repository, and keep just yours, but merging into it the two changes of that patch.

**Comment by ahukkanen** [comment]
Sure. I think they are actually already included since they come from this commit:
https://github.com/tedious/JShrink/commit/91105810dafedba0390608d7465abd602beb6410

That is included in the patch.

**Comment by mlocati** [comment]
> That is included in the patch.

You are right, I just read the first patch. So, I'd just drop the current patch

**Comment by ahukkanen** [comment]
> So, I'd just drop the current patch

Done already at e6c779790e1ea591bfa458e4e2b4b598a87e1c64.

**Comment by mlocati** [comment]
I tried this with an installation where we already had the previous patch applied.

Here's the relevant parts:

```
$ composer update concrete5/dependency-patches

  - Updating concrete5/dependency-patches (1.2.0 => dev-master 0f13eb6):  Checking out 0f13eb61ea

Applying patch concrete5/dependency-patches/Update to upstream version 1.3.2 to tedivm/jshrink... patch was already applied.

```

So I think we have to do something to "revert" the previous patch, maybe splitting it in two, so that the "reverting" patch may fail (when the previous patch isn't already applied). In any case, the second one (the one in this PR) should be executed by composer-patcher

**Comment by ahukkanen** [comment]
I think it is just loading it from some cache where you have already applied the patch.

I get the exact same message when I try the update to the concrete5 main repository by pulling the dependency from this git repository.

I don't completely understand how those patches are applied in the background (haven't looked into it) but it seems to be working correctly.

---

To test:

Clone the c5 repository:

```
$ git clone git@github.com:concrete5/concrete5.git c5dptest
```

Run composer install:

```
$ cd c5dptest
$ composer install
```

Add the following lines in the composer.json at the root of the project:

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/concrete5/dependency-patches.git"
    }
  ],
```

And change the following line:

```
  "require": {
    ...
    "concrete5/dependency-patches": "dev-master"
  },
```

Run composer update for the dependency patches package:


```
$ composer update concrete5/dependency-patches
```

Now, check the file at `vendor/tedivm/jshrink/src/JShrink/JShrink.php`.

It should have all the patches applied.

I was particularly looking for the changes done here:
https://github.com/tedious/JShrink/pull/84/files

**Comment by mlocati** [comment]
> I don't completely understand how those patches are applied in the background (haven't looked into it)

They simply run a command like this:

```sh
patch -p1 --no-backup-if-mismatch -N -d "path/to/vendor/tedivm/jshrink" -i "path/to/file.patch"
```

**Comment by ahukkanen** [comment]
Yeah, hard to say where that message is coming from. I also get the `patch was already applied` message from all the current patches when I run them against a clean cache directory.

To verify, you can change the local cache directory with the test provided above before running the first `composer install`:

```
$ mkdir .composer-cache
$ composer config cache-dir "$PWD/.composer-cache"
```

After this, copy the current `Minifier.php` version for reference (before updating the dependency to this repository):

```
$ cp concrete/vendor/tedivm/jshrink/src/JShrink/Minifier.php Minifier-orig.php
```

Then run the rest of the test and finally compare the `Minifier.php` after applying the latest patch:

```
$ diff Minifier-orig.php concrete/vendor/tedivm/jshrink/src/JShrink/Minifier.php
```

You can see that it has changed regardless of the message.

**Comment by mlocati** [comment]
With https://github.com/concrete5/dependency-patches/pull/4, starting from the state after dependency-patches v1.3.0 applied its patches, we have:

```
Applying patch concrete5/dependency-patches/Fix continue switch in FileGenerator and MethodReflection to tedivm/jshrink... patch was already applied.
Applying patch concrete5/dependency-patches/Update to upstream version 1.3.2 to tedivm/jshrink... done.
```

**Comment by mlocati** [comment]
(and BTW we should really change that "Fix continue switch in FileGenerator and MethodReflection" description, it was a mistake of mine)

**Comment by mlocati** [comment]
@ahukkanen maybe we are using two different version of the `patch` command (I'm using the one that comes with git for Windows).
What do you have now with the current master of this repo?

**Comment by ahukkanen** [comment]
@mlocati When pulling from master I now get this when updating `concrete5/dependency-patches` with a clean composer cache:

```
Applying patch concrete5/dependency-patches/Fix continue switch in Minifier to tedivm/jshrink... patch was already applied.
Applying patch concrete5/dependency-patches/Update to upstream version 1.3.2 to tedivm/jshrink... done.
```

**Comment by mlocati** [comment]
See https://github.com/concrete5/concrete5/pull/7930

**Pull request merged**
